Prevents java.lang.NoClassDefFoundError when searching for platform
Recently, we added `Platform.nextTraceIdHigh()`, which compiled against
a JDK 7 type `ThreadLocalRandom` due to being indirectly referenced in
a utility method. This changes the signature such that it can't imply
this anymore.

This also removes AutoValue from platform as it adds unnecessary classes
to the jar.